#!/usr/bin/env bash
set -e 
PROBLEM_0=("Tsiligirides Set 1" "../etc/tsiligrides_problem1/" "--output="resultsProblem1"")
PROBLEM_1=("Tsiligirides Set 2" "../etc/tsiligrides_problem2/" "--output="resultsProblem2"")
PROBLEM_2=("Tsiligirides Set 3" "../etc/tsiligrides_problem3/" "--output="resultsProblem3"")
PROBLEM_3=("Chao diamond-shaped Set" "../etc/chao_set64-diamond/" "--output="resultsSet64"")
PROBLEM_4=("Chao squared-shaped Set" "../etc/chao_set66-square/chao_set_66_1_060.txt" "--output="resultsSet66"")


#PROBLEMS=(
#  PROBLEM_0[@]
#  PROBLEM_1[@]
#  PROBLEM_2[@]
#  PROBLEM_3[@]
#  PROBLEM_4[@]
#)

#echo "$@"

PROBLEMS=(
  PROBLEM_4[@]
)


#./fourphase --name="Tsiligirides Set 1" --problem="etc/tsiligrides_problem1/tsiligirides_problem_1_budget_75.txt"

TEST_IDS=( 6 )
CONFIGS_NEIGHBORHOODS=("0.0" "0.2" "0.5" "1.0" "1.5")
CONFIGS_RADIUS=("0.0" "0.3" "0.5" "1.0" "1.5" )



COUNT_CONFIGS_NEIGHBORHOODS=${#CONFIGS_NEIGHBORHOODS[@]}
COUNT_CONFIGS_RADIUS=${#CONFIGS_RADIUS[@]}
COUNT_PROBLEMS=${#PROBLEMS[@]}
COUNT_TEST_IDS=${#TEST_IDS[@]}

for ((problemi=0; problemi<$COUNT_PROBLEMS; problemi++))
do

for ((configineihg=0; configineihg<$COUNT_CONFIGS_NEIGHBORHOODS; configineihg++))
do

neigh=${CONFIGS_NEIGHBORHOODS[configineihg]}
config_neigh="--neighborhood-radius="$neigh

for ((configirad=0; configirad<$COUNT_CONFIGS_RADIUS; configirad++))
do

radius=${CONFIGS_RADIUS[configirad]}
config_rad="--dop-radius="$radius

echo $config_neigh
echo $config_rad

for ((testi=0; testi<$COUNT_TEST_IDS; testi++))
do
  TEST_ID=${TEST_IDS[$testi]}
  PROBLEM_NAME=${!PROBLEMS[problemi]:0:1}
  PROBLEM_PATH=${!PROBLEMS[problemi]:1:1}
  outputFolder="results/resultsSet66_nr"$neigh"_r"$radius"_run_"$TEST_ID
  echo $TEST_ID
  echo $outputFolder
  PROBLEM_CONFIG="--output="$outputFolder""
  echo $PROBLEM_CONFIG
  PROBLEM_FILES=`ls ${PROBLEM_PATH}`
  echo "NAME ${PROBLEM_NAME}"
  echo "PATH ${PROBLEM_PATH}"
  #echo "FILES ${FILES_}"
  for file_name in ${PROBLEM_FILES} ;
  do
	echo "test file ""$file_name"
        echo "with additional config $config_neigh and $config_rad"
        echo "problem name ""$PROBLEM_NAME"
  	../main --name="$PROBLEM_NAME" --problem="$PROBLEM_PATH" "$@" $PROBLEM_CONFIG $config_neigh $config_rad
  done

done

done

done

done
